#eureka:
#  client:
#  # 用于指定是否把当前的客户端实例注册到 Eureka 服务器中
#    registerWithEureka: false
#  # 用于指定是否从 Eureka 服务器上拉取已注册的服务信息
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
server:
  port: 8761
eureka:
  instance:
    hostname: eureka1
  client:
      serviceUrl:
   defaultZone: http://eureka2:8762/eureka/
