
zuul:
  # 配置路由
  routes:
    system:
      url: http://localhost:8081
  sensitive-headers:
#  # 配置限流
#  ratelimit:
#    enabled: false
#    # 对应存储类型(用来统计存储统计信息)
#    repository: redis
#    # 默认策略
#    default-policy-list:
#      # 每秒允许多少个请求
#      - limit: 2
#        # 刷新时间(单位秒)
#        refresh-interval: 1
#        # 根据什么统计
#        type:
#          -url
#          -httpmethod
#    policy-list:
#      system:
#        - limit: 2
#            # 刷新时间(单位秒)
#            refresh-interval: 1
#            # 根据什么统计
#            type:
#              -url
#              -httpmethod
server:
  port: 9090