server:
  port: 9195
  address: 0.0.0.0

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: soul-bootstrap
  cloud:
    nacos:
      discovery:
        server-addr: 10.226.73.73:8886


management:
  health:
    defaults:
      enabled: false




soul:
  file:
    enabled: true
  corss:
    enabled: true
  sync:
    websocket:
      urls: ws://localhost:9095/websocket