#spring:
#  application:
#    name: system-application
#  # 数据源配置项
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/study_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123456
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  # redis配置
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: 123456


logging:
  level:
    org:
      training:
        cloud:
          system: DEBUG





#auth:
#  security:
#    not-auth-urls:
#      - /sys/login
#      - /swagger-ui
#      - /**/api-docs/
#      - /*.html
#      - /**/*.html
#      - /**/*.css
#      - /**/*.js
#      - /webjars/**
#      - /v3/**
#      - /swagger-resources/**
#
#
## Swagger 配置项
#training:
#  swagger:
#    title: system
#    description: 用户相关系统
#    version: 1.0.0
#    base-package: org.training.cloud.system
#
#
#
#
#
#
## MyBatis Plus 配置项
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
#  global-config:
#    db-config:
#      id-type: AUTO
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#  mapper-locations: classpath*:mapper/*.xml
#  type-aliases-package: org.training.cloud.system.entity




